### ISSUE TITLE
[Core] Minimal and lower cost Lambda-RDS access configuration

### ISSUE THREAD

**Issue by despot** [intuit/Trapheus#18]
Provide a way for a user to generate a minimal and lower cost Lambda-RDS access configuration.

**Context**:
Currently, lambda functions have a VPC, subnets and security group linked to them when generated. Lambdas are connected to a VPC in your account, and by default the function can't access the RDS (or other services) if VPC doesn't provide access (either by routing outbound traffic to a [NAT gateway](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) in a public subnet, or having a [VPC endpoint](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html), both of which incur cost or require more setup). 

**How**: 
Provide a sam deploy parameter that will disable the linkage between the VPC/sg and will let [lambdas run in a default Lambda owned VPC that has access to RDS (and other AWS services)](https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html#vpc-internet).

**Issue**:
Typically, linking your own VPC to the lambdas and not setting addition NAT gateway or VPC endpoint configuration will result in a ["Connect timeout on endpoint URL: "https://rds.[region].amazonaws.com/"" or "Task timed out after 3.00 seconds" issue](https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-networking.html).
Typical output from the create snapshot lambda in this case is:
Connect timeout on endpoint URL: "https://rds.eu-west-1.amazonaws.com/"
Traceback (most recent call last):
  File "/var/task/snapshot_function.py", line 22, in lambda_create_dbinstance_snapshot
    util.eval_snapshot_exception(error, instance_id, rds)
  File "/opt/python/utility.py", line 71, in eval_snapshot_exception
    raise custom_exceptions.SnapshotCreationException(error_message)

**Comment by despot** [comment]
I'll take this issue.

**Comment by despot** [comment]
Not able to assign myself to the issue, so @namitad feel free to assign me, and also set the labels: "enhancement" and "good first issue". Did you limit the ability of contributors to not be able to add labels and assign themselves as Assignees? Perhaps I am missing something..

**Comment by despot** [comment]
@stationeros @RiyaJohn can you check this issue and reviewe the accompanying PR as well: https://github.com/intuit/Trapheus/pull/19/files ?
@namitad I believe you would do this by default.
Can we kindly move this forward faster as important and useful? (I lost quite a lot of time to figure out how to run Trapheus as free as possible)
